# [START runtime]
#service: aspira-frontend
#service: icon-frontend
#service: iconcx-frontend
#service: 3c-frontend
#service: ace-frontend
#service: optimus-frontend
#service: pfizer-territory
#service: jbcpl-frontend
#service: maxx-frontend
#service: vikrant-frontend
#service: cimune-frontend
#service: govaxx-frontend
#service: tx-frontend
#service: training-channelitix
#service: aspira-plus-frontend
service: chl-frontend
runtime: python27
threadsafe: yes
# [END runtime]

handlers:

- url: /(.*\.(gif|png|jpg|css|js|otf|eot|svg|ttf|woff|woff2)(|\.map))$
  static_files: dist/\1
  upload: dist/(.*)(|\.map)
  secure: always

- url: /(.*)
  static_files: dist/index.html
  upload: dist/index.html
  secure: always

# Temporary setting to keep gcloud from uploading not required files for deployment
skip_files:
- ^node_modules$
- ^app\.yaml
- ^README\..*
- \.gitignore
- ^\.git$
- ^grunt\.js
- ^src$
- ^e2e$
- \.editorconfig
- ^karma\.config\.js
- ^package\.json
- ^protractor\.conf\.js
- ^tslint\.json
